import {SkinType, SliderType} from "../enums";
import {IRangeSliderEvent} from "./range-slider-event";

export interface IBaseRangeSliderConfiguration {
    skin: SkinType; // Set slider theme [Default: flat]
    type: SliderType;    // Choose slider type, could be `single` - for one handle, or `double` for two handles [Default: single]
    minInterval: number;    // Set minimum diapason between sliders. Only for **double** type [Default: -]
    maxInterval: number;    // Set minimum maximum between sliders. Only for **double** type [Default: -]
    dragInterval: boolean;   // Allow user to drag whole range. Only for **double** type [Default: false]
    values: (number | string)[];     // Set up your own array of possible slider values. They could be numbers or strings. If the values array is set up, min, max and step param, can no longer be changed [Default: []]
    prettyValues: (number | string)[];
    fromFixed: boolean;   // Fix position of left (or single) handle [Default: false]
    fromShadow: boolean;   // Highlight the limits for left handle [Default: false]
    toFixed: boolean;   // Fix position of right handle [Default: false]
    toShadow: boolean;   // Highlight the right handle [Default: false]
    prettifyEnabled: boolean;   // Improve readability of long numbers: 10000000 &rarr; 10 000 000 [Default: true]
    prettifySeparator: string;    // Set up your own separator for long numbers: 10000000 &rarr; 10,000,000 etc. [Default:  ]
    prettify?: (num: number) => string; // Set up your own prettify function. Can be anything. For example, you can set up unix time as slider values and than transform them to cool looking dates [Default: null]
    forceEdges: boolean;   // Sliders handles and tooltips will be always inside it's container [Default: false]
    keyboard: boolean;   // Activates keyboard controls. Move left: &larr;, &darr;, A, S. Move right: &rarr;, &uarr;, W, D. [Default: true]
    grid: boolean;   // Enables grid of values above the slider [Default: true]
    gridMargin: boolean;   // Set left and right grid gaps [Default: true]
    gridSnap: boolean;   // Snap grid to sliders step (step param). If activated, grid_num will not be used. Max steps = 50 [Default: false]
    hideMinMax: boolean;   // Hides **min** and **max** labels [Default: false]
    hideFromTo: boolean;   // Hides **from** and **to** labels [Default: false]
    prefix?: string;    // Set prefix for values. Will be set up right before the number: **$**100 [Default: ]
    postfix?: string;    // Set postfix for values. Will be set up right after the number: 100**k** [Default: ]
    maxPostfix?: string;    // Special postfix, used only for maximum value. Will be showed after handle will reach maximum right position. For example **0 — 100+** [Default: ]
    decorateBoth: boolean;   // Used for **double** type and only if prefix or postfix was set up. Determine how to decorate close values. For example: **$10k — $100k** or **$10 — 100k** [Default: true]
    valuesSeparator: string;    // Set your own separator for close values. Used for **double** type. Default: **10 — 100**. Or you may set: **10 to 100, 10 + 100, 10 &rarr; 100** etc. [Default:  - ]
    inputValuesSeparator: string;    // Separator for **double** values in input value property. `<input value="25;42"> [Default:  ; ]
    disable: boolean;   // Locks slider and makes it inactive. Input is disabled too. Invisible to forms [Default: false]
    block: boolean;   // Locks slider and makes it inactive. Input is NOT disabled. Can be send with forms [Default: false]
    extraClasses: string;    // Traverse extra CSS-classes to sliders container [Default: —]
    callbackScope?: object;       // Scope for callbacks. Pass any object [Default: null]
    onStart?: (obj: IRangeSliderEvent) => void; // Callback. Is called on slider start. Gets all slider data as a 1st attribute [Default: null]
    onChange?: (obj: IRangeSliderEvent) => void; // Callback. IS called on each values change. Gets all slider data as a 1st attribute [Default: null]
    onFinish?: (obj: IRangeSliderEvent) => void; // Callback. Is called when user releases handle. Gets all slider data as a 1st attribute [Default: null]
    onUpdate?: (obj: IRangeSliderEvent) => void; // Callback. Is called when slider is modified by external methods `update` or `reset [Default: null]
}

export interface IRangeSliderConfiguration<T> extends IBaseRangeSliderConfiguration {
    min: T;    // Set slider minimum value [Default: 10]
    max: T;    // Set slider maximum value [Default: 100]
    from: T;       // Set start position for left handle (or for single handle) [Default: min]
    to: T;         // Set start position for right handle [Default: max]
    step: T;       // Set sliders step. Always > 0. Could be fractional [Default: 1]
    fromMin: T;    // Set minimum limit for left (or single) handle [Default: min]
    fromMax: T;    // Set maximum limit for left (or single) handle [Default: max]
    toMin: T;      // Set minimum limit for right handle [Default: min]
    toMax: T;      // Set maximum limit for right handle [Default: max]
    gridNum: T;    // Number of grid units [Default: 4]
}